// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC52sJNfiiEJOS-2FzfdRnIJKR16dAVeMk',
    appId: '1:190651208146:web:2820c0d33453b7ab90b80b',
    messagingSenderId: '190651208146',
    projectId: 'gp-auth2',
    authDomain: 'gp-auth2.firebaseapp.com',
    storageBucket: 'gp-auth2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ5zib_-XAXkiHatqJd3onVB6QzKLUDVA',
    appId: '1:190651208146:android:4e9d07f8b8f1850b90b80b',
    messagingSenderId: '190651208146',
    projectId: 'gp-auth2',
    storageBucket: 'gp-auth2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCseGARdZIfjLIIfweYPlmXksfTORrR5rc',
    appId: '1:190651208146:ios:29a288647dbb2d3790b80b',
    messagingSenderId: '190651208146',
    projectId: 'gp-auth2',
    storageBucket: 'gp-auth2.appspot.com',
    iosBundleId: 'com.example.gp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCseGARdZIfjLIIfweYPlmXksfTORrR5rc',
    appId: '1:190651208146:ios:656c35bcc2f9447290b80b',
    messagingSenderId: '190651208146',
    projectId: 'gp-auth2',
    storageBucket: 'gp-auth2.appspot.com',
    iosBundleId: 'com.example.gp2.RunnerTests',
  );
}
